micronaut:
  application:
    name: questionnaire
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:K1BIJE7ZQbgx4uyyujEjp/4/SxIKPZswVZDsN3B9DY8=}"'
datasources:
  default:
    url: jdbc:mysql://localhost:3306/questionnaire
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: ${MYSQL_PASSWORD}
    schema-generate: CREATE_DROP
    dialect: MYSQL
jpa.default.properties.hibernate.hbm2ddl.auto: update
